apiVersion: apps/v1
kind: Deployment
metadata:
  name: zomato-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: zomato
  template:
    metadata:
      labels:
        app: zomato
    spec:
      containers:
      - name: zomato
        image: divyanshu067/zomato-clone:8
        ports:
        - containerPort: 8000
